name: Github Actions 실행하기

on:
  push:
    branches:
      - master

jobs:
  Manual-deployment-Job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-action-test
        run: echo "This is the first cicd step"

      - name: Github repository 소스 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설치하기
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: applcation.yml 추가
        run:
          echo ${{secrets.APPLICATION_YML}} >> ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: |
          chmod +x ./gradlew --warning-mode all
          ./gradlew clean build --warning-mode all

        # 현재 폴더로 옮기면서 이름만 변경한다
      - name: jar 파일명 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar app.jar

#      - name: EC2로 jar 파일 전송하기
#        run:
#
#      - name: SSH로 EC2에 접속하기(프로세스 실행)
#        run: