name: Github Actions 실행하기

on:
  push:
    branches:
      - master

jobs:
  Manual-deployment-Job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-action-test
        run: echo "This is the first cicd step"

      - name: applcation.yml 추가
        run: |
          pwd
          ls ./src/main/
          echo ${{secrets.APPLICATION_YML}} >> ./src/main/resources/application.yml